spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
server.tomcat.max-http-form-post-size=35MB
server.tomcat.max-swallow-size=35MB
spring.jackson.default-property-inclusion=non_null
spring.main.banner-mode=off
logging.level.root=WARN
logging.level.io.github.seuh.esig=INFO
logging.level.io.github.seuh.esig.EsigApiApplication=WARN
logging.level.eu.europa.esig.dss.tsl.function.converter.DigitalIdentityListTypeConverter=ERROR
esig.lotl.url=https://ec.europa.eu/tools/lotl/eu-lotl.xml
esig.lotl.cache-dir=${ESIG_LOTL_CACHE_DIR:./.cache/lotl}
esig.lotl.refresh-interval=${ESIG_LOTL_REFRESH_INTERVAL:PT6H}
esig.revocation.refresh-interval=${ESIG_REVOCATION_REFRESH_INTERVAL:PT1H}
